spring:
  profiles:
    active: dev
  application:
    name: geometry-api
  config.import:
      - classpath:properties/persistence.yml
      - classpath:properties/openApi.yml
      - classpath:properties/security.yml

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml



logging:
  level:
    org:
      springframework:
        web=DEBUG: INFO
        security=DEBUG: INFO
server.port: 8888






